export const SCREEN_WIDTH = 200;
export const SCREEN_HEIGHT = 200;
export const WORLD_WIDTH = SCREEN_WIDTH * 2;
export const WORLD_HEIGHT = SCREEN_HEIGHT * 2;
export const GROUND_HEIGHT = SCREEN_HEIGHT / 10;
export const CEIL_HEIGHT = SCREEN_HEIGHT / 10;
export const WALL_WIDTH = SCREEN_WIDTH / 10;
export const WALL_HEIGHT = WORLD_HEIGHT - GROUND_HEIGHT - CEIL_HEIGHT;
export const PLATFORM_WIDTH =
  WORLD_HEIGHT - WALL_WIDTH * 2 - SCREEN_WIDTH * 0.4;
export const PLATFORM_HEIGHT = SCREEN_HEIGHT / 10;
